name: Build the Website

on:
  push:
    branches: [ master ]
    paths: [ 'sitesrc/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
	
    steps:
    - name: Checkout website repo
      uses: actions/checkout@v2

    - name: Checkout site generator
      uses: actions/checkout@v2
      with:
        repository: cicirello/site-generator
        token: ${{ secrets.PAT }} 
        path: sitegenerator

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Build and run the site generator
      run: |
        cd sitegenerator
        javac src/*.java -d .
        cd ..
        java -cp "./sitegenerator" BibParser cicirello-pubs-web.bib p b


