name: Build the Website

on:
  push:
    branches: [ staging ]
    paths: [ '.sitesrc/**.config', '.sitesrc/**.bib', '.sitesrc/**.json', 'styles/style.css' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the Website

    steps:
    - name: Checkout website repo
      uses: actions/checkout@v4

    - name: Checkout site generator
      uses: actions/checkout@v4
      with:
        repository: cicirello/site-generator
        ssh-key: ${{ secrets.DEPLOY_KEY_SITE_GEN }} 
        path: sitegenerator

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build and run the site generator
      run: |
        cd sitegenerator/sitegen
        mvn package
        cd ..
        cd ..
        java -jar sitegenerator/sitegen/target/SiteGen-1.0.0-jar-with-dependencies.jar cicirello-pubs-web.bib p b
        if [[ `git status --porcelain` ]]; then
          git config --global user.name 'Vincent A. Cicirello'
          git config --global user.email 'cicirello@users.noreply.github.com'
          git add -A
          git commit -m "Website updated by custom site generator"
        fi

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7.0.3
      with:
        title: "Website updated by custom site generator"
        body: > 
          Website updates produced by custom site generator. 
        commit-message: "Website updated by custom site generator"
        author: Vincent A. Cicirello <cicirello@users.noreply.github.com>
        committer: Vincent A. Cicirello <cicirello@users.noreply.github.com>
        branch: create-pull-request/website-update
        delete-branch: true
