name: Generate search index 

on:
  push:
    branches: [ staging ]
    paths: [ 'sitemap.xml' ]

jobs:
  build_index:
    runs-on: ubuntu-latest
    name: Index the website

    steps:
    - name: Checkout website repo
      uses: actions/checkout@v4

    - name: Checkout site generator
      uses: actions/checkout@v4
      with:
        repository: cicirello/site-generator
        ssh-key: ${{ secrets.DEPLOY_KEY_SITE_GEN }} 
        path: sitegenerator

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build and run the website indexer
      run: |
        cd sitegenerator/indexer
        mvn package
        cd ..
        cd ..
        java -jar sitegenerator/indexer/target/WebsiteIndexer-1.0.0-jar-with-dependencies.jar sitemap.xml https://www.cicirello.org/ > js/search_index.js
        if [[ `git status --porcelain` ]]; then
          cd sitegenerator
          javac index-version-inc/*.java -d .
          cd ..
          java -cp "./sitegenerator" IncrementIndexVersion js/site_search.min.js
          git config --global user.name 'Vincent A. Cicirello'
          git config --global user.email 'cicirello@users.noreply.github.com'
          git add -A
          git commit -m "Website search index automated update"
        fi

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6.1.0
      with:
        title: "Website search index automated update"
        body: > 
          Website search index automated update. 
        commit-message: "Website search index automated update"
        author: Vincent A. Cicirello <cicirello@users.noreply.github.com>
        committer: Vincent A. Cicirello <cicirello@users.noreply.github.com>
        branch: create-pull-request/index-update
        delete-branch: true

